repos:
  - repo: local
    hooks:
      - id: crustyc-syntax
        name: Crusty Syntax Check
        entry: cargo run --bin crustyc -- --check
        language: system
        files: \.crst$
        pass_filenames: true
      
      - id: cargo-fmt
        name: Cargo Format Check
        entry: cargo fmt -- --check
        language: system
        files: \.rs$
        pass_filenames: false
      
      - id: cargo-clippy
        name: Cargo Clippy
        entry: cargo clippy --
        language: system
        files: \.rs$
        pass_filenames: false
        args: ["-D", "warnings"]
